# coding: utf-8

"""
    oxd-server

    oxd-server  # noqa: E501

    OpenAPI spec version: 4.0
    Contact: yuriyz@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.get_access_token_by_refresh_token_params import GetAccessTokenByRefreshTokenParams  # noqa: E501
from swagger_client.rest import ApiException


class TestGetAccessTokenByRefreshTokenParams(unittest.TestCase):
    """GetAccessTokenByRefreshTokenParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetAccessTokenByRefreshTokenParams(self):
        """Test GetAccessTokenByRefreshTokenParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_access_token_by_refresh_token_params.GetAccessTokenByRefreshTokenParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
