# coding: utf-8

"""
    oxd-server

    oxd-server  # noqa: E501

    OpenAPI spec version: 4.0
    Contact: yuriyz@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.get_logout_uri_response import GetLogoutUriResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestGetLogoutUriResponse(unittest.TestCase):
    """GetLogoutUriResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetLogoutUriResponse(self):
        """Test GetLogoutUriResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_logout_uri_response.GetLogoutUriResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
