# coding: utf-8

"""
    oxd-server

    oxd-server  # noqa: E501

    OpenAPI spec version: 4.0
    Contact: yuriyz@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.get_jwks_params import GetJwksParams  # noqa: E501
from swagger_client.rest import ApiException


class TestGetJwksParams(unittest.TestCase):
    """GetJwksParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetJwksParams(self):
        """Test GetJwksParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_jwks_params.GetJwksParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
