# coding: utf-8

"""
    oxd-server

    oxd-server  # noqa: E501

    OpenAPI spec version: 4.0
    Contact: yuriyz@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.rs_resource import RsResource  # noqa: E501
from swagger_client.rest import ApiException


class TestRsResource(unittest.TestCase):
    """RsResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRsResource(self):
        """Test RsResource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.rs_resource.RsResource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
