# coding: utf-8

"""
    oxd-server

    oxd-server  # noqa: E501

    OpenAPI spec version: 4.0
    Contact: yuriyz@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.get_authorization_url_response import GetAuthorizationUrlResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestGetAuthorizationUrlResponse(unittest.TestCase):
    """GetAuthorizationUrlResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetAuthorizationUrlResponse(self):
        """Test GetAuthorizationUrlResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_authorization_url_response.GetAuthorizationUrlResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
