# coding: utf-8

"""
    oxd-server

    oxd-server  # noqa: E501

    OpenAPI spec version: 4.0
    Contact: yuriyz@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.developers_api import DevelopersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDevelopersApi(unittest.TestCase):
    """DevelopersApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.developers_api.DevelopersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_access_token_by_refresh_token(self):
        """Test case for get_access_token_by_refresh_token

        Get Access Token By Refresh Token  # noqa: E501
        """
        pass

    def test_get_authorization_url(self):
        """Test case for get_authorization_url

        Get Authorization Url  # noqa: E501
        """
        pass

    def test_get_client_token(self):
        """Test case for get_client_token

        Get Client Token  # noqa: E501
        """
        pass

    def test_get_discovery(self):
        """Test case for get_discovery

        Get OP Discovery Configuration  # noqa: E501
        """
        pass

    def test_get_json_web_key_set(self):
        """Test case for get_json_web_key_set

        Get JSON Web Key Set  # noqa: E501
        """
        pass

    def test_get_logout_uri(self):
        """Test case for get_logout_uri

        Get Logout URL  # noqa: E501
        """
        pass

    def test_get_tokens_by_code(self):
        """Test case for get_tokens_by_code

        Get Tokens By Code  # noqa: E501
        """
        pass

    def test_get_user_info(self):
        """Test case for get_user_info

        Get User Info  # noqa: E501
        """
        pass

    def test_health_check(self):
        """Test case for health_check

        Health Check  # noqa: E501
        """
        pass

    def test_introspect_access_token(self):
        """Test case for introspect_access_token

        Introspect Access Token  # noqa: E501
        """
        pass

    def test_introspect_rpt(self):
        """Test case for introspect_rpt

        Introspect RPT  # noqa: E501
        """
        pass

    def test_register_site(self):
        """Test case for register_site

        Register Site  # noqa: E501
        """
        pass

    def test_remove_site(self):
        """Test case for remove_site

        Remove Site  # noqa: E501
        """
        pass

    def test_uma_rp_get_claims_gathering_url(self):
        """Test case for uma_rp_get_claims_gathering_url

        UMA RP Get Claims Gathering URL  # noqa: E501
        """
        pass

    def test_uma_rp_get_rpt(self):
        """Test case for uma_rp_get_rpt

        UMA RP Get RPT  # noqa: E501
        """
        pass

    def test_uma_rs_check_access(self):
        """Test case for uma_rs_check_access

        UMA RS Check Access  # noqa: E501
        """
        pass

    def test_uma_rs_protect(self):
        """Test case for uma_rs_protect

        UMA RS Protect Resources  # noqa: E501
        """
        pass

    def test_update_site(self):
        """Test case for update_site

        Update Site  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
