# coding: utf-8

"""
    oxd-server

    oxd-server  # noqa: E501

    OpenAPI spec version: 4.0
    Contact: yuriyz@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class IntrospectAccessTokenResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'active': 'bool',
        'client_id': 'str',
        'username': 'str',
        'scope': 'list[str]',
        'token_type': 'str',
        'sub': 'str',
        'aud': 'str',
        'iss': 'str',
        'exp': 'int',
        'iat': 'int',
        'nbf': 'int',
        'jti': 'str',
        'acr_values': 'list[str]',
        'extension_field': 'str'
    }

    attribute_map = {
        'active': 'active',
        'client_id': 'client_id',
        'username': 'username',
        'scope': 'scope',
        'token_type': 'token_type',
        'sub': 'sub',
        'aud': 'aud',
        'iss': 'iss',
        'exp': 'exp',
        'iat': 'iat',
        'nbf': 'nbf',
        'jti': 'jti',
        'acr_values': 'acr_values',
        'extension_field': 'extension_field'
    }

    def __init__(self, active=None, client_id=None, username=None, scope=None, token_type=None, sub=None, aud=None, iss=None, exp=None, iat=None, nbf=None, jti=None, acr_values=None, extension_field=None):  # noqa: E501
        """IntrospectAccessTokenResponse - a model defined in Swagger"""  # noqa: E501

        self._active = None
        self._client_id = None
        self._username = None
        self._scope = None
        self._token_type = None
        self._sub = None
        self._aud = None
        self._iss = None
        self._exp = None
        self._iat = None
        self._nbf = None
        self._jti = None
        self._acr_values = None
        self._extension_field = None
        self.discriminator = None

        self.active = active
        self.client_id = client_id
        self.username = username
        self.scope = scope
        self.token_type = token_type
        self.sub = sub
        self.aud = aud
        self.iss = iss
        self.exp = exp
        self.iat = iat
        self.nbf = nbf
        self.jti = jti
        self.acr_values = acr_values
        self.extension_field = extension_field

    @property
    def active(self):
        """Gets the active of this IntrospectAccessTokenResponse.  # noqa: E501


        :return: The active of this IntrospectAccessTokenResponse.  # noqa: E501
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this IntrospectAccessTokenResponse.


        :param active: The active of this IntrospectAccessTokenResponse.  # noqa: E501
        :type: bool
        """
        if active is None:
            raise ValueError("Invalid value for `active`, must not be `None`")  # noqa: E501

        self._active = active

    @property
    def client_id(self):
        """Gets the client_id of this IntrospectAccessTokenResponse.  # noqa: E501


        :return: The client_id of this IntrospectAccessTokenResponse.  # noqa: E501
        :rtype: str
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id):
        """Sets the client_id of this IntrospectAccessTokenResponse.


        :param client_id: The client_id of this IntrospectAccessTokenResponse.  # noqa: E501
        :type: str
        """
        if client_id is None:
            raise ValueError("Invalid value for `client_id`, must not be `None`")  # noqa: E501

        self._client_id = client_id

    @property
    def username(self):
        """Gets the username of this IntrospectAccessTokenResponse.  # noqa: E501


        :return: The username of this IntrospectAccessTokenResponse.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this IntrospectAccessTokenResponse.


        :param username: The username of this IntrospectAccessTokenResponse.  # noqa: E501
        :type: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def scope(self):
        """Gets the scope of this IntrospectAccessTokenResponse.  # noqa: E501


        :return: The scope of this IntrospectAccessTokenResponse.  # noqa: E501
        :rtype: list[str]
        """
        return self._scope

    @scope.setter
    def scope(self, scope):
        """Sets the scope of this IntrospectAccessTokenResponse.


        :param scope: The scope of this IntrospectAccessTokenResponse.  # noqa: E501
        :type: list[str]
        """
        if scope is None:
            raise ValueError("Invalid value for `scope`, must not be `None`")  # noqa: E501

        self._scope = scope

    @property
    def token_type(self):
        """Gets the token_type of this IntrospectAccessTokenResponse.  # noqa: E501


        :return: The token_type of this IntrospectAccessTokenResponse.  # noqa: E501
        :rtype: str
        """
        return self._token_type

    @token_type.setter
    def token_type(self, token_type):
        """Sets the token_type of this IntrospectAccessTokenResponse.


        :param token_type: The token_type of this IntrospectAccessTokenResponse.  # noqa: E501
        :type: str
        """
        if token_type is None:
            raise ValueError("Invalid value for `token_type`, must not be `None`")  # noqa: E501

        self._token_type = token_type

    @property
    def sub(self):
        """Gets the sub of this IntrospectAccessTokenResponse.  # noqa: E501


        :return: The sub of this IntrospectAccessTokenResponse.  # noqa: E501
        :rtype: str
        """
        return self._sub

    @sub.setter
    def sub(self, sub):
        """Sets the sub of this IntrospectAccessTokenResponse.


        :param sub: The sub of this IntrospectAccessTokenResponse.  # noqa: E501
        :type: str
        """
        if sub is None:
            raise ValueError("Invalid value for `sub`, must not be `None`")  # noqa: E501

        self._sub = sub

    @property
    def aud(self):
        """Gets the aud of this IntrospectAccessTokenResponse.  # noqa: E501


        :return: The aud of this IntrospectAccessTokenResponse.  # noqa: E501
        :rtype: str
        """
        return self._aud

    @aud.setter
    def aud(self, aud):
        """Sets the aud of this IntrospectAccessTokenResponse.


        :param aud: The aud of this IntrospectAccessTokenResponse.  # noqa: E501
        :type: str
        """
        if aud is None:
            raise ValueError("Invalid value for `aud`, must not be `None`")  # noqa: E501

        self._aud = aud

    @property
    def iss(self):
        """Gets the iss of this IntrospectAccessTokenResponse.  # noqa: E501


        :return: The iss of this IntrospectAccessTokenResponse.  # noqa: E501
        :rtype: str
        """
        return self._iss

    @iss.setter
    def iss(self, iss):
        """Sets the iss of this IntrospectAccessTokenResponse.


        :param iss: The iss of this IntrospectAccessTokenResponse.  # noqa: E501
        :type: str
        """
        if iss is None:
            raise ValueError("Invalid value for `iss`, must not be `None`")  # noqa: E501

        self._iss = iss

    @property
    def exp(self):
        """Gets the exp of this IntrospectAccessTokenResponse.  # noqa: E501

        number of seconds since January 1 1970 UTC, indicating when this token will expire  # noqa: E501

        :return: The exp of this IntrospectAccessTokenResponse.  # noqa: E501
        :rtype: int
        """
        return self._exp

    @exp.setter
    def exp(self, exp):
        """Sets the exp of this IntrospectAccessTokenResponse.

        number of seconds since January 1 1970 UTC, indicating when this token will expire  # noqa: E501

        :param exp: The exp of this IntrospectAccessTokenResponse.  # noqa: E501
        :type: int
        """
        if exp is None:
            raise ValueError("Invalid value for `exp`, must not be `None`")  # noqa: E501

        self._exp = exp

    @property
    def iat(self):
        """Gets the iat of this IntrospectAccessTokenResponse.  # noqa: E501

        number of seconds since January 1 1970 UTC, indicating when the token was issued at  # noqa: E501

        :return: The iat of this IntrospectAccessTokenResponse.  # noqa: E501
        :rtype: int
        """
        return self._iat

    @iat.setter
    def iat(self, iat):
        """Sets the iat of this IntrospectAccessTokenResponse.

        number of seconds since January 1 1970 UTC, indicating when the token was issued at  # noqa: E501

        :param iat: The iat of this IntrospectAccessTokenResponse.  # noqa: E501
        :type: int
        """
        if iat is None:
            raise ValueError("Invalid value for `iat`, must not be `None`")  # noqa: E501

        self._iat = iat

    @property
    def nbf(self):
        """Gets the nbf of this IntrospectAccessTokenResponse.  # noqa: E501

        number of seconds since January 1 1970 UTC, indicating when the token not to be used before  # noqa: E501

        :return: The nbf of this IntrospectAccessTokenResponse.  # noqa: E501
        :rtype: int
        """
        return self._nbf

    @nbf.setter
    def nbf(self, nbf):
        """Sets the nbf of this IntrospectAccessTokenResponse.

        number of seconds since January 1 1970 UTC, indicating when the token not to be used before  # noqa: E501

        :param nbf: The nbf of this IntrospectAccessTokenResponse.  # noqa: E501
        :type: int
        """
        if nbf is None:
            raise ValueError("Invalid value for `nbf`, must not be `None`")  # noqa: E501

        self._nbf = nbf

    @property
    def jti(self):
        """Gets the jti of this IntrospectAccessTokenResponse.  # noqa: E501

        a unique identifier for the JWT  # noqa: E501

        :return: The jti of this IntrospectAccessTokenResponse.  # noqa: E501
        :rtype: str
        """
        return self._jti

    @jti.setter
    def jti(self, jti):
        """Sets the jti of this IntrospectAccessTokenResponse.

        a unique identifier for the JWT  # noqa: E501

        :param jti: The jti of this IntrospectAccessTokenResponse.  # noqa: E501
        :type: str
        """
        if jti is None:
            raise ValueError("Invalid value for `jti`, must not be `None`")  # noqa: E501

        self._jti = jti

    @property
    def acr_values(self):
        """Gets the acr_values of this IntrospectAccessTokenResponse.  # noqa: E501


        :return: The acr_values of this IntrospectAccessTokenResponse.  # noqa: E501
        :rtype: list[str]
        """
        return self._acr_values

    @acr_values.setter
    def acr_values(self, acr_values):
        """Sets the acr_values of this IntrospectAccessTokenResponse.


        :param acr_values: The acr_values of this IntrospectAccessTokenResponse.  # noqa: E501
        :type: list[str]
        """
        if acr_values is None:
            raise ValueError("Invalid value for `acr_values`, must not be `None`")  # noqa: E501

        self._acr_values = acr_values

    @property
    def extension_field(self):
        """Gets the extension_field of this IntrospectAccessTokenResponse.  # noqa: E501


        :return: The extension_field of this IntrospectAccessTokenResponse.  # noqa: E501
        :rtype: str
        """
        return self._extension_field

    @extension_field.setter
    def extension_field(self, extension_field):
        """Sets the extension_field of this IntrospectAccessTokenResponse.


        :param extension_field: The extension_field of this IntrospectAccessTokenResponse.  # noqa: E501
        :type: str
        """
        if extension_field is None:
            raise ValueError("Invalid value for `extension_field`, must not be `None`")  # noqa: E501

        self._extension_field = extension_field

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IntrospectAccessTokenResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IntrospectAccessTokenResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
