# coding: utf-8

"""
    oxd-server

    oxd-server  # noqa: E501

    OpenAPI spec version: 4.0
    Contact: yuriyz@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class UmaRsProtectParams(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'oxd_id': 'str',
        'overwrite': 'bool',
        'resources': 'list[RsResource]'
    }

    attribute_map = {
        'oxd_id': 'oxd_id',
        'overwrite': 'overwrite',
        'resources': 'resources'
    }

    def __init__(self, oxd_id=None, overwrite=None, resources=None):  # noqa: E501
        """UmaRsProtectParams - a model defined in Swagger"""  # noqa: E501

        self._oxd_id = None
        self._overwrite = None
        self._resources = None
        self.discriminator = None

        self.oxd_id = oxd_id
        self.overwrite = overwrite
        self.resources = resources

    @property
    def oxd_id(self):
        """Gets the oxd_id of this UmaRsProtectParams.  # noqa: E501


        :return: The oxd_id of this UmaRsProtectParams.  # noqa: E501
        :rtype: str
        """
        return self._oxd_id

    @oxd_id.setter
    def oxd_id(self, oxd_id):
        """Sets the oxd_id of this UmaRsProtectParams.


        :param oxd_id: The oxd_id of this UmaRsProtectParams.  # noqa: E501
        :type: str
        """
        if oxd_id is None:
            raise ValueError("Invalid value for `oxd_id`, must not be `None`")  # noqa: E501

        self._oxd_id = oxd_id

    @property
    def overwrite(self):
        """Gets the overwrite of this UmaRsProtectParams.  # noqa: E501


        :return: The overwrite of this UmaRsProtectParams.  # noqa: E501
        :rtype: bool
        """
        return self._overwrite

    @overwrite.setter
    def overwrite(self, overwrite):
        """Sets the overwrite of this UmaRsProtectParams.


        :param overwrite: The overwrite of this UmaRsProtectParams.  # noqa: E501
        :type: bool
        """
        if overwrite is None:
            raise ValueError("Invalid value for `overwrite`, must not be `None`")  # noqa: E501

        self._overwrite = overwrite

    @property
    def resources(self):
        """Gets the resources of this UmaRsProtectParams.  # noqa: E501


        :return: The resources of this UmaRsProtectParams.  # noqa: E501
        :rtype: list[RsResource]
        """
        return self._resources

    @resources.setter
    def resources(self, resources):
        """Sets the resources of this UmaRsProtectParams.


        :param resources: The resources of this UmaRsProtectParams.  # noqa: E501
        :type: list[RsResource]
        """
        if resources is None:
            raise ValueError("Invalid value for `resources`, must not be `None`")  # noqa: E501

        self._resources = resources

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UmaRsProtectParams, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UmaRsProtectParams):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
